import Header from '@/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex flex-1 gap-4 w-full items-center flex-grow flex-col p-4">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
